[package]
name = "mayeul"
version = "0.1.0"
authors = ["Mayeul d'Avezac <1085775-mdavezac@users.noreply.gitlab.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1"
petgraph = "0.5.1"
